[[v0_0_21]]
= Release notes versión 0.0.21

== Mejoras
* *Lanzador*: Se incluye nuevo diseño de la ventana splash durante el arranque de las aplicaciones de negocio.

== Incidencias
* *Uninstall*: Se corrige el problema de borrado del acceso directo del escritorio de Windows cuando se realizaba la
desinstalación de una aplicación por línea de comandos.
* *Caché de librerías*: Se fuerza la descarga de la librería que estaba en caché cuando no se puede verificar su integridad
en lugar de abortar el proceso de arranque de la aplicación de negocio.
* *Acceso directo*: Se soluciona problema iniciando la aplicación de negocio desde el acceso directo de escritorio y el modo offline.
* *Librerías nativas*: Se soluciona un problema que provocaba que no se cargaran correctamente las dll's de las librerías
nativas de las aplicaciones de negocio.
* *Barra de tareas*: Se soluciona el problema del icono que se muestra en la barra de tareas de Windows. En ocasiones se
mostraba el icono de la aplicación de negocio en lugar del icono de AMIGA Java Launcher.

