[[intro]]
= Introducción
include::attributes.adoc[]

== Introducción

Amiga Java Launcher está formado por dos herramientas que ofrecen una alternativa al despliegue tradicional
de las aplicaciones de negocio mediante la tecnología Java WebStart. Estas herramientas son: el plugin de maven (responsable
de empaquetar la aplicación de negocio), y la aplicación (lanzador) que es quien realmente arranca la aplicación de negocio.

El principal objetivo del plugin de Maven es permitir a los desarrolladores empaquetar las aplicaciones de negocio para
su distribución. El plugin maneja la generación del archivo descriptor IJLP, pero también se encarga de la selección y preparación de las
dependencias de la aplicación, realizando tanto la firma de los recursos como la firma del propio archivo descriptor.

NOTE: El plugin requiere la versión *Maven 3.5.0 ó superior* para funcionar correctamente.

El lanzador se encarga de descargar los recursos necesarios de la aplicación de negocio en el directorio de instalación,
comprobar si existe una versión más actual de esos recursos para descargarlos, realizar las verificaciones de seguridad
y arrancar la aplicación de negocio.

== Características

Plugin de maven:

* Generación del archivo descriptor (_.ijlp_).
* Firmado de los recursos y archivo descriptor (_.ijlp_).
* Gestión de recursos nativos.
Posibilidad de añadir dependencias dependiendo del sistema operativo y/o arquitectura.
* Gestión de librerías modulares (Java 9+).
* Gestión de recursos externos que no forman parte de la aplicación de negocio (imágenes, archivos de configuración, etc.)

Lanzador de aplicaciones:

* Descargar los recursos de la aplicación de negocio.
* Comprobación de actualización de recursos de la aplicación.
* Verificaciones de seguridad.
* Arranque de la aplicación de negocio.
