= Catálogo de JVM's
:docinfo: shared,private
:favicon: ./images/favicon.png

El lanzador de aplicaciones no necesita la instalación de Java en el PC de usuario. Las aplicaciones
de negocio que se ejecutan mediante `Amiga Java Launcher` utilizan una máquina virtual de Java que está contenida en un catálogo
de máquinas virtuales (`jvm-catalog`) que se distribuyen con el instalador de `Amiga Java Launcher`.
La versión de Java disponible por el momento es: 1.8. Esta máquina virtual es la misma que actualmente está instalada en los equipos de los usuarios de Inditex.

El almacenamiento de las máquinas virtuales en este directorio se hace por Sistema Operativo, arquitectura y versión de la JRE. Para cada versión de JRE existirán tantos subdirectorios como revisiones de la JRE existan.

```bash

jvm_catalog
  ├─ windows
  │   └─ x86_64
  │       └─ 1.8.0_202
  │          └─  rev_1.0
  └─ jvm-catalog.xml
```

El fichero `jvm-catalog.xml` contiene el listado de todas las máquinas virtuales disponibles en el repositorio.
El contenido de este fichero es:

[source,xml]
----
<jvm-catalog version="1.0">
    <os id="windows" path="/windows">
        <arch id="x86_64" pattern="^(x8664|amd64|ia32e|em64t|x64)$" path="/x86_64">
            <jvm version="1.8.0_202" path="/1.8.0_202" rev="1.0"></jvm>
        </arch>
    </os>
</jvm-catalog>
----

* Sistema operativo (`<os>`).
Se especifica el identificador del sistema operativo (id) y la ruta en la que se encuentran sus recursos (path).
* Arquitectura (`arch`).
Se especifica el identificador de la arquitectura (id) y la ruta en la que se encuentran sus recursos (path);
* Máquina virtual (`<jvm>`).
Se especifica la versión de la máquina virtual (version), la ruta en la que se encuentran los recursos y la revisión para esta versión.
Por cada versión podrán existir tantas revisiones como se desee.
Además también se indica si es la versión por defecto de la máquina virtual para ejecutar las aplicaciones mediante el archivo descriptor *jnlp*.


